### ISSUE TITLE
I'm getting a failure

### ISSUE THREAD

**Issue by SolarAquarion** [m-pilia/vim-pkgbuild#1]
"PKGBUILD" 1L, 1B                                                                                                  
Error detected while processing function <SNR>260_VimCloseCallback[11]..<SNR>260_VimExitCallback[22]..function <SNR
>260_VimCloseCallback[11]..<SNR>260_VimExitCallback[15]..<lambda>19[1]..<SNR>258_ExitCallback[28]..<SNR>257_HandleE
xit:                                                                                                               
line   24:                                                                                                         
E117: Unknown function: ale_linters#sh#shellcheck#Handle                                                           
Error detected while processing function <SNR>260_VimCloseCallback:                                                
line   11:                                                                                                         
E171: Missing :endif                                                                                               
[coc.nvim] RPC: Connected to Discord Gateway!                                                                      
Error detected while processing function <SNR>260_VimCloseCallback[11]..<SNR>260_VimExitCallback[22]..function <SNR
>260_VimCloseCallback[11]..<SNR>260_VimExitCallback[15]..<lambda>22[1]..<SNR>258_ExitCallback[28]..<SNR>257_HandleE
xit:                                                                                                               
line   24:                                                                                                         
E117: Unknown function: ale_linters#sh#shellcheck#Handle                                                           
Error detected while processing function <SNR>260_VimCloseCallback:                                                
line   11:                                                                                                         
E171: Missing :endif                                                                                               
Error detected while processing function <SNR>260_VimCloseCallback[11]..<SNR>260_VimExitCallback[22]..function <SNR
>260_VimCloseCallback[11]..<SNR>260_VimExitCallback[15]..<lambda>24[1]..<SNR>258_ExitCallback[28]..<SNR>257_HandleE
xit:                                                                                                               
line   24:                                                                                                         
E117: Unknown function: ale_linters#sh#shellcheck#Handle                                                           
Error detected while processing function <SNR>260_VimCloseCallback:

**Comment by m-pilia** [comment]
@SolarAquarion Thanks for the report, the name of the handler changed in a refactoring of ALE, I am updating it.

**Comment by SolarAquarion** [comment]
Vim(helptags):E154: Duplicate tag "Updpkgsums" in file /home/solaraquarion/.cache/dein/.cache/vimrc/.dein/doc/vim-pkgbuild.txt

**Comment by m-pilia** [comment]
@SolarAquarion Thanks for noting, should be fixed in #3
